- hosts: webservers
  become: true
  become_user: root
  vars_files:
    - vars/infra.yml
  roles:
    - { role: itcraftsmanpl.php7 }
    - { role: geerlingguy.apache }
    - { role: geerlingguy.pip }
    - { role: geerlingguy.supervisor }

  tasks:
    - name: 'create supervisor group'
      group:
        name: supervisor
        state: present

    - name: 'create user'
      user:
        name: mpwar-tfm
        group: supervisor
        password: 123