Mpwar\DataProcessor\Infrastructure\Domain\EnrichedDocument\DoctrineEnrichedDocument:
  type: entity
  repositoryClass: \Mpwar\DataProcessor\Infrastructure\Domain\EnrichedDocument\DoctrineEnrichedDocumentRepository
  table: enriched_document
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    rawDocumentId:
      column: raw_document_id
      type: string
      length: 36
    keyword:
      type: string
      length: 255
    source:
      type: string
      length: 255
    content:
      type: text
    createdAt:
      column: created_at
      type: datetimetz
    author:
      type: string
      length: 255
    authorLocation:
      column: author_location
      type: string
      length: 2
    language:
      type: string
      length: 2
    metadata:
      type: text